### PR TITLE
Update major dependencies

### PR DESCRIPTION
**Pull request by XhmikosR**
Requires #92.

Split from #92 so that you can release a patch version with the other PRs first :)

Notes:

* it's probably worth waiting for a new release from https://github.com/pahen/detective-typescript/pulls
* I'll adapt CI after the other PRs have landed

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
A huge thanks for all of your contributions. I really appreciate the helping hand keeping this project up to date. Awesome work.

**Comment by XhmikosR** [comment]
NP, glad I could help!

I'd say let's wait until https://github.com/pahen/detective-typescript/pulls are sorted and then merge this PR and cut a new major version. In the meantime, you can cut a new patch version from master :)

**Comment by mrjoelkemp** [comment]
Sounds good. Released a new patch version.

**Comment by XhmikosR** [comment]
@mrjoelkemp can you please check my PRs in the dependents projects? I've spent quite some time on them, it'd be a pity to have them unmerged/unreleased :/

**Comment by mrjoelkemp** [comment]
> @mrjoelkemp can you please check my PRs in the dependents projects? I've spent quite some time on them, it'd be a pity to have them unmerged/unreleased :/

Yeah, I might be late, but I'll always try to get to them as soon as I can carve out the time and energy. Thanks for all of your work.

**Pull request merged**
