### PR TITLE
feat: add CSS (PostCSS dialect)

### PR DESCRIPTION
**Pull request by joscha**
This adds the capability to follow references of CSS files. Detective, see https://github.com/joscha/node-detective-postcss

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Thanks so much for contributing @joscha. Awesome work here and the detective looks great. I just cut a new minor version. Thanks again.

**Comment by joscha** [comment]
Awesome @mrjoelkemp! One thing that I was thinking about when writing the detective: references to local images, etc. are technically also dependencies. They are leave nodes, but not less important, do you think these should be part of the CSS detective dependency list? I think they need to be, as I personally want to use detective to create a graph of all dependencies, but I saw that none of the other detectives (sass, scss, stylus) do that. What are your thoughts?

**Comment by mrjoelkemp** [comment]
> They are leave nodes, but not less important, do you think these should be part of the CSS detective dependency list? I think they need to be, as I personally want to use detective to create a graph of all dependencies, but I saw that none of the other detectives (sass, scss, stylus) do that. What are your thoughts?

Do you mean via sniffing `url()` properties? If so, that makes sense for completeness. The other detectives don't do it at the moment because I didn't have a need for that functionality downstream. 

For my own knowledge, if you had a relative path as the value in `url()`, would that get resolved to an absolute path at PostCSS build time? 

I'd be open to supporting an optional flag to include images.

Are there any other asset types that you think should be included?

**Comment by joscha** [comment]
> @joscha Do you mean via sniffing url() properties? If so, that makes sense for completeness. The other detectives don't do it at the moment because I didn't have a need for that functionality downstream.

Yes, correct. I want to use https://github.com/dependents/node-dependency-tree to find out which files were affected by a change and for that I would need images, etc. as well (by the way, could you have a look at https://github.com/dependents/node-dependency-tree/pull/82, please? It updates precinct).

> For my own knowledge, if you had a relative path as the value in url(), would that get resolved to an absolute path at PostCSS build time?

No, it would stay relative. It would be possible to write a plugin that claculates the path though, would that be needed for the output? E.g. is each detective expected to return absolute paths or paths relative to the dir from which precint is run?

> I'd be open to supporting an optional flag to include images.

👍 

> Are there any other asset types that you think should be included?

I think all image formats, font files, etc. that you would potentially reference from CSS.

By the way, as I just have you here: I saw that some detectives (https://github.com/pahen/detective-typescript for example) also handles an AST as parameter.
1. What is the rationale behind that?
2. The AST passed is an AST produced by the respective detective?
3. There seems to be some logic around which files get passed an AST and which don't that doesn't seem to completely make sense to me, do you mind elaborating, please?

**Comment by mrjoelkemp** [comment]
> by the way, could you have a look at dependents/node-dependency-tree#82, please? It updates precinct

Done and thanks!

> No, it would stay relative. It would be possible to write a plugin that claculates the path though, would that be needed for the output?

Yes and that's what https://github.com/dependents/node-filing-cabinet currently does for all of the other detectives. You can think of dependency tree as taking a file, pulling out its dependencies via precinct then resolving that dependency to a file on the filesystem via filing-cabinet. Then, for each resolved dependency, you recursively perform the same extraction.

> E.g. is each detective expected to return absolute paths or paths relative to the dir from which precint is run?

Relative paths and then filing-cabinet does the absolute path resolution as explained above.

> What is the rationale behind that? (regarding accepting an AST)

It avoids a secondary parse of the file into an AST. As in, we need an ast for a few operations, one is to pull out dependencies, and another is to sniff the type of module it is (which JS import system, for example: ES6, CJS, or AMD). It would be really expensive to parse the raw text file (into an AST) redundantly for these operations. So the detectives accept an AST to avoid the additional parse. That logic of whether or not to do a parse is in node-source-walk (the shared [AST traversal library](https://github.com/dependents/node-source-walk/blob/ffc28ee365f0ca32eca5abaeb86152270986b1ff/index.js#L98) for most of the detectives).

> There seems to be some logic around which files get passed an AST and which don't that doesn't seem to completely make sense to me, do you mind elaborating, please?

Do you mind linking to examples? I'm not sure which logic you're referring to.

**Comment by joscha** [comment]
> Yes and that's what https://github.com/dependents/node-filing-cabinet currently does for all of the other detectives. You can think of dependency tree as taking a file, pulling out its dependencies via precinct then resolving that dependency to a file on the filesystem via filing-cabinet. Then, for each resolved dependency, you recursively perform the same extraction.

Got it, just saw the fallback resolver code, which you linked in dependents/node-dependency-tree#82 - I think that should work fine for CSS.

>> What is the rationale behind that? (regarding accepting an AST)
> It avoids a secondary parse of the file into an AST. As in, we need an ast for a few operations, one is to pull out dependencies, and another is to sniff the type of module it is (which JS import system, for example: ES6, CJS, or AMD). It would be really expensive to parse the raw text file (into an AST) redundantly for these operations. So the detectives accept an AST to avoid the additional parse. That logic of whether or not to do a parse is in node-source-walk (the shared AST traversal library for most of the detectives).

Ah yes, that makes sense. the css-detective doesn't use node-source-walk, as postcss provides a walker, so I am safe there I suppose (e.g. I wondered whether I needed to accept an AST there).

> Do you mind linking to examples? I'm not sure which logic you're referring to.

For CSS, the type is set to `css` here: https://github.com/dependents/node-precinct/blob/26d7a4c449f7d321621bc1742643f6e2725dc88e/index.js#L144, so `precinct(...)`  gets called with the content and `{ type: 'css' }`, which then goes into the else branch to run the detective, but in https://github.com/dependents/node-precinct/blob/26d7a4c449f7d321621bc1742643f6e2725dc88e/bin/cli.js#L25 it is just run with the source (as a string), the type is not set, so I would have expected https://github.com/dependents/node-precinct/blob/26d7a4c449f7d321621bc1742643f6e2725dc88e/index.js#L43 to be truthy (as `!type` is true and `typeof content` is `string`, and that would blow up for the CSS, but it doesn't and I am not sure what I am missing.

**Comment by mrjoelkemp** [comment]
> it is just run with the source (as a string), the type is not set, so I would have expected

The CLI script (bin/cli.js) is a different beast that is only used by folks who want to invoke precinct programmatically in their shell. I haven't looked at that as precinct has evolved, so it's very likely to be handicapped. When dependency-tree invokes precinct, it's not leveraging that script, which is why everything works as expected.

I haven't received that many requests for the cli to get updated, so it's not something that I'm budgeting time for. I'm open to PRs to make that script work/better though.

**Comment by joscha** [comment]
> Are there any other asset types that you think should be included?
> 
>> I think all image formats, font files, etc. that you would potentially reference from CSS.

@mrjoelkemp This change is in version `2.1.0` of the `detective-postcss` via the option `{ url: true }`

**Comment by mrjoelkemp** [comment]
@joscha just bumped the dep version and added docs. Great work!

**Pull request merged**
