### PR TITLE
Output cli on multiple lines

### LINKED ISSUE #76: Export regular text instead of array in cli
CLI tools don't expect to receive input in the JavaScript array format, I don't know what to do with this, I'd have to parse it as JS:

```sh
$ precinct file.js
[ 'a', 'b' ]

````

bur rather it should just be a plain list:

```sh
$ precinct file.js
a
b
````

### PR DESCRIPTION
**Pull request by fregante**
Fixes #76

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Thanks for fixing this @fregante! Appreciate the help. I released a new major version for this change.

**Comment by fregante** [comment]
Why did you take my code and commit it yourself instead of merging this PR?

**Comment by mrjoelkemp** [comment]
I wanted to edit the commit message to indicate that it was a breaking change. I don't use a CHANGELOG file and instead rely on the commit history between tags as the changelog. Annotating the commit with references to the issue and PR are also a bit out of habit. No worries though, you're still the author of the commit :) Thanks again.

**Comment by fregante** [comment]
That can be done via commit squashing when merging 😁

**Pull request closed without merging**
