### PR TITLE
add support for TypeScript

### PR DESCRIPTION
**Pull request by davidfirst**

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Thanks @davidfirst. I'm working on fixing the build by downgrading detective-typescript to es5 to work with older versions of node: https://github.com/pahen/detective-typescript/pull/3. 

Once that's done, it would be great to have some tests on this PR before we land it. Let me know if you'd have time to contribute those tests.

**Comment by davidfirst** [comment]
Sounds good. Yes, I guess I will have some time to write some tests.

**Comment by mrjoelkemp** [comment]
@davidfirst that detective-typescript fix landed. You're good to write some tests for typescript support. Feel free to ping me to merge when ready. Thanks again for your help.

**Comment by davidfirst** [comment]
@mrjoelkemp the tests are ready. I tried to cover the various import types of TypeScript. Hopefully, I got them all.

**Comment by mrjoelkemp** [comment]
Thanks so much for contributing @davidfirst. Great work here! 

This was landed in a new minor release.

**Pull request merged**
